package com.boa.eagls.government.dao;

import com.boa.eagls.government.exceptions.NBWarning;
import com.boa.eagls.government.exceptions.NoDataFoundException;
import com.boa.eagls.government.exceptions.system.EaglsDAOError;
import com.boa.eagls.government.constants.service.Role;

import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

import org.apache.log4j.Logger;

/**
 * User: OlegK
 * Date: 25.06.2003
 * Time: 17:34:58
 * To change this template use Options | File Templates.
 */
public class DAOBaseNew extends DAOUtil {

    public DAOBaseNew(){
        super();
    }


    /**
     *  This Method will add user's available program type to the query
     *  to restrict the results by program types as well.
     *
     * @param	sqlStmt	the SQL statement to send.
     * @return	the results generated by adding the AND conditions.
     *			This method is guaranteed not to return null.
     * @exception	EaglsDAOError	an error occurred on the database while executing
     *						SQLStatement.
     **/
    protected static final StringBuffer appendPTCheckByUserPT(StringBuffer sqlStmt,
                                                 String currentBaseRole,
                                                 char[] programTypes) throws EaglsDAOError {
        try {
            String role = currentBaseRole;
            if (!(Role.GCSU.equals(role)) && !(Role.GSA.equals(role)) && !(Role.FMS.equals(role)) && !(Role.AH.equals(role))) {
                sqlStmt.append(authorizeProgramType("a.PROG_TYPE", currentBaseRole, programTypes));
            }
        } catch (NBWarning e) {
            throw new EaglsDAOError(e.getDetailedMessage());
        }
        return sqlStmt;
    }

    /**
     * Generates an "AND" SQL clause to filter accounts by the
     * current user's Program Types.  This method assumes the user's
     * current role has program types.  An exception will be thrown
     * no program types are found in the session state.
     *
     * @param	column	the table column to filter.
     * @return	the generated "AND" SQL clause.
     * @exception	NBWarning	could not find the current user's Program Types.
     */
    protected static final String authorizeProgramType(String column, String currentBaseRole, char[] programTypes)
            throws NBWarning{
        StringBuffer buf = new StringBuffer(" AND ");
        buf.append(column);
        buf.append(" IN (");

        // TODO Modify for real implementation
//        char[] programTypes = currentProgramTypes;
        if (programTypes == null || programTypes.length == 0) {
            throw new NBWarning("SYS_E0003:DataAccessAdapter::Current user's program types not found");
        }

        buf.append("'" + programTypes[0] + "'");
        for (short i = 1; i < programTypes.length; i++) {
            buf.append(", '" + programTypes[i] + "'");
        }

        buf.append(")\n");
        return buf.toString();
    }
}
